"""Component 7 — Integrator.

Assemble the committed per-step modules, in dependency order, into a single
runnable PySpark pipeline. Each step is written to ``steps/<label>.py`` and a
generated ``pipeline.py`` wires them together: it threads each step's output
DataFrame into the ``inputs`` dict of its downstream consumers, keyed by dataset
name. External (source) datasets are supplied by the caller.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass

from ..models import NodeStatus
from .pipeline import PipelineResult


@dataclass
class IntegrationArtifacts:
    out_dir: str
    steps_dir: str
    runner_path: str
    manifest_path: str
    step_files: dict[str, str]


_RUNNER_TEMPLATE = '''"""GENERATED by sas2spark — full PySpark pipeline.

Do not edit by hand; regenerate from the SAS source instead.
Run order is topological. Each entry: (module label, primary output key, input keys).
"""
from __future__ import annotations

import importlib.util
import os

_STEPS_DIR = os.path.join(os.path.dirname(__file__), "steps")

# (label, primary_output_dataset, [input_dataset_keys])
STEPS = {steps!r}

EXTERNAL_INPUTS = {external!r}
FINAL_OUTPUTS = {finals!r}


def _load(label):
    path = os.path.join(_STEPS_DIR, label + ".py")
    spec = importlib.util.spec_from_file_location("step_" + label, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.transform


def run_pipeline(spark, sources: dict) -> dict:
    """Execute the full pipeline.

    `sources` maps each EXTERNAL_INPUTS dataset key to a Spark DataFrame.
    Returns a dict of every produced dataset keyed by name (incl. FINAL_OUTPUTS).
    """
    missing = [k for k in EXTERNAL_INPUTS if k not in sources]
    if missing:
        raise ValueError("missing source datasets: %s" % missing)

    datasets = dict(sources)
    for label, out_key, in_keys in STEPS:
        transform = _load(label)
        inputs = {{k: datasets[k] for k in in_keys if k in datasets}}
        absent = [k for k in in_keys if k not in datasets]
        if absent:
            raise ValueError(
                "step %s is missing upstream datasets %s "
                "(a dependency may have failed translation)" % (label, absent)
            )
        result = transform(spark, inputs)
        if out_key:
            datasets[out_key] = result
    return datasets


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(
        "Import run_pipeline(spark, sources) from your driver; "
        "this module is not meant to be run standalone."
    )
'''


def _step_module_header(node) -> str:
    sas = node.step.text.strip()
    indented = "\n".join("#   " + ln for ln in sas.splitlines())
    return (
        f"# GENERATED by sas2spark — translation of SAS step {node.step.index} "
        f"({node.step.kind.value}{('/' + node.step.proc_name) if node.step.proc_name else ''}).\n"
        f"# Original SAS:\n{indented}\n\n"
    )


def integrate(result: PipelineResult, out_dir: str, *, include_unverified: bool = False) -> IntegrationArtifacts:
    steps_dir = os.path.join(out_dir, "steps")
    os.makedirs(steps_dir, exist_ok=True)

    eligible_status = {NodeStatus.PASSED}
    if include_unverified:
        eligible_status |= {NodeStatus.TRANSLATED, NodeStatus.NEEDS_HUMAN}

    step_files: dict[str, str] = {}
    steps_spec: list[tuple[str, str, list[str]]] = []

    for node in result.nodes:
        if node.python_code is None:
            continue
        if node.status not in eligible_status:
            continue
        label = node.module_name
        path = os.path.join(steps_dir, f"{label}.py")
        with open(path, "w", encoding="utf-8") as f:
            f.write(_step_module_header(node))
            f.write(node.python_code.rstrip() + "\n")
        step_files[label] = path

        primary_out = node.step.outputs[0].key if node.step.outputs else ""
        in_keys = [r.key for r in node.step.inputs]
        steps_spec.append((label, primary_out, in_keys))

    runner_src = _RUNNER_TEMPLATE.format(
        steps=steps_spec,
        external=sorted(result.graph.external_inputs),
        finals=sorted(result.graph.final_outputs),
    )
    runner_path = os.path.join(out_dir, "pipeline.py")
    with open(runner_path, "w", encoding="utf-8") as f:
        f.write(runner_src)

    manifest = {
        "settings": result.settings.to_dict(),
        "summary": result.summary(),
        "graph": result.graph.to_dict(),
        "nodes": [
            {
                "index": n.step.index,
                "label": n.module_name,
                "status": n.status.value,
                "attempts": n.attempts,
                "evals": [
                    {"phase": r.phase.value, "passed": r.passed, "skipped": r.skipped,
                     "summary": r.summary}
                    for r in n.eval_results
                ],
                "notes": n.notes,
            }
            for n in result.nodes
        ],
    }
    manifest_path = os.path.join(out_dir, "manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    return IntegrationArtifacts(
        out_dir=out_dir,
        steps_dir=steps_dir,
        runner_path=runner_path,
        manifest_path=manifest_path,
        step_files=step_files,
    )
